# Generated by Django 4.2.7 on 2023-11-14 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30)),
                ('interesting', models.TextField(blank=True)),
                ('birdDay', models.DateTimeField(default=datetime.datetime(2023, 11, 14, 18, 0, 41, 962968))),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_money', models.BooleanField(default=True)),
            ],
        ),
    ]
