# Generated by Django 4.2.7 on 2023-11-14 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_student_birdday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBook', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('yearPublication', models.IntegerField(default=0)),
                ('publishingHouse', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='birdDay',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 2, 47, 6, 816804)),
        ),
    ]
