# Generated by Django 4.2.7 on 2023-11-28 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_book_alter_student_birdday'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='birdDay',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 2, 7, 34, 310477)),
        ),
    ]
