# Generated by Django 4.2.7 on 2023-11-28 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_book_slug_alter_student_birdday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birdDay',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 2, 10, 13, 957977)),
        ),
    ]
