# Generated by Django 4.2.7 on 2023-11-28 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_alter_book_slug_alter_student_birdday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='birdDay',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 2, 49, 50, 444389)),
        ),
    ]
