# Generated by Django 4.2.7 on 2023-11-29 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_alter_student_birdday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birdDay',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 3, 10, 16, 884148)),
        ),
    ]
